[2023-05-31T02:25:41.870+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: captura_dados.created_folders_task manual__2023-05-31T02:25:39.815241+00:00 [queued]>
[2023-05-31T02:25:41.885+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: captura_dados.created_folders_task manual__2023-05-31T02:25:39.815241+00:00 [queued]>
[2023-05-31T02:25:41.886+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-05-31T02:25:41.886+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-05-31T02:25:41.886+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-05-31T02:25:41.914+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): created_folders_task> on 2023-05-31 02:25:39.815241+00:00
[2023-05-31T02:25:41.922+0000] {standard_task_runner.py:55} INFO - Started process 2934 to run task
[2023-05-31T02:25:41.928+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'captura_dados', 'created_folders_task', 'manual__2023-05-31T02:25:39.815241+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/captura_dados.py', '--cfg-path', '/tmp/tmp_o70v8if']
[2023-05-31T02:25:41.931+0000] {standard_task_runner.py:83} INFO - Job 74: Subtask created_folders_task
[2023-05-31T02:25:42.063+0000] {task_command.py:388} INFO - Running <TaskInstance: captura_dados.created_folders_task manual__2023-05-31T02:25:39.815241+00:00 [running]> on host 5219a5ad576c
[2023-05-31T02:25:42.190+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=test@test.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=captura_dados
AIRFLOW_CTX_TASK_ID=created_folders_task
AIRFLOW_CTX_EXECUTION_DATE=2023-05-31T02:25:39.815241+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-31T02:25:39.815241+00:00
[2023-05-31T02:25:42.191+0000] {logging_mixin.py:137} INFO - Pasta data já existe!
[2023-05-31T02:25:42.199+0000] {logging_mixin.py:137} INFO - Diretório 'olist_brasil/data/engineer' já existe.
[2023-05-31T02:25:42.200+0000] {logging_mixin.py:137} INFO - Diretório 'olist_brasil/data/raw' já existe.
[2023-05-31T02:25:42.200+0000] {logging_mixin.py:137} INFO - Diretório 'olist_brasil/data/refined' já existe.
[2023-05-31T02:25:42.200+0000] {logging_mixin.py:137} INFO - Diretório 'olist_brasil/data/transient' já existe.
[2023-05-31T02:25:42.200+0000] {logging_mixin.py:137} INFO - Diretório 'olist_brasil/data/trusted' já existe.
[2023-05-31T02:25:42.200+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-05-31T02:25:42.216+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=captura_dados, task_id=created_folders_task, execution_date=20230531T022539, start_date=20230531T022541, end_date=20230531T022542
[2023-05-31T02:25:42.267+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-05-31T02:25:42.293+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
